
spring.application.name=lokaloka
spring.datasource.url=jdbc:mysql://localhost:3306/lokaloka?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Bangkok
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=mysql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true

# C?u hình server ?? ch?y trên t?t c? IP
server.address=0.0.0.0
server.port=8080

#Flyway
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true
spring.flyway.enabled=true

#Cloudinary
cloudinary.cloud-name=dheynv6n8
cloudinary.api-key=528735669639166
cloudinary.api-secret=QgQh6cot703d8wD7vkF0gU6zOzQ
# Gi?i h?n kích th??c file upload (50MB)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

#gemini
gemini.api.key=AIzaSyBGlU3jVC9X-HP-0-8h1P371LEKHdTbKfA
gemini.model.name=gemini-2.0-flash-exp
gemini.temperature=0.7
gemini.top-p=0.95
gemini.top-k=64
gemini.max-output-tokens=65536


# C?u hình OAuth2 v?i Google
spring.security.oauth2.client.registration.google.client-id=123422089993-a7nieopueqakrbe0661b16goeuso0luq.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=YOUR_GOOGLE_CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo


jwt.secret=1Rum7/TcMm4ETruzoRKrcI6ML+iyktFd3fWGCmqKbtKt/CS8H5ViWEbqfFsB5gQ4TcyptOPuXR/lFmLZCH4X7g==

spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Bangkok

server.forward-headers-strategy=native
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs








